name: autodqm
channels:
  - conda-forge
  - defaults
dependencies:
  - certifi==2020.06.20
  - chardet==3.0.4
  - idna==2.10
  - lxml==4.5.2
  - numpy==1.19.4
  - plotly==4.12.0
  - python-kaleido
  - requests==2.24.0
  - requests-futures==1.0.0
  - scikit-learn==0.20.4
  - scipy==1.5.3
  - tqdm==4.47.0
  - uproot==4.0.1
  - urllib3==1.25.10
  - python>=3.3

